### ISSUE TITLE
rule assign_fragments crashes due to pyarrow problem

### ISSUE THREAD

**Issue by Mittmich** [nanoporetech/Pore-C-Snakemake#30]
When running the pipeline, I encountered sporadic crashes in the assign-fragments step that seem to be related to an open issue of `aws-sdk-cpp`, a dependency of `pyarrow`. Details of the issue can be found [here](https://github.com/aws/aws-sdk-cpp/issues/1809).

I could fix the problem by freezing the `aws-sdk-cpp` version in the `pore_c.yml` environment to version `1.8.186`, which could be an option as a short-term workaround.

**Comment by aallahyar** [comment]
Thanks @Mittmich!
Indeed I encountered a similar problem and through google I made the same conclusion.

To be clear (and as @Mittmich mentions), simply modify your `pore_c.yml` files to (i.e. add the last line):

```yaml
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pore-c==0.4.0
  - python==3.8
  - aws-sdk-cpp=1.8.186=h9ad65fb_2
```
